require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake

AllCops:
  Exclude:
    - binstub/**/*
    - exe/**/*
    - vendor/**/*
    - Gemfile*
  NewCops: enable

Gemspec/DeprecatedAttributeAssignment:
  Enabled: false

Gemspec/RequireMFA:
  Enabled: false

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Max: 150

Metrics/AbcSize:
  Max: 35

Metrics/BlockLength:
  Exclude:
    - llm_cli.gemspec
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/MethodLength:
  Max: 40

Metrics/ModuleLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Max: 15

Naming/FileName:
  Exclude:
    - Rakefile

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
