#!/usr/local/bin/ruby

if ENV['VO_DEBUGGING']
  require_relative '../lib/llm_util'
else
  require 'llm_util'
end

def main
  OllamaDriver.help 'Error: file name must be specified' if ARGV.empty?
  OllamaDriver.help 'Error: invalid syntax' if ARGV.length != 1

  # Default should be: model: 'llava', timeout: 5*60
  options = OllamaDriver.parse_options

  OllamaDriver.new(options).describe_image ARGV[0]
end

main
