#!/usr/local/bin/ruby

require_relative '../lib/ollama_driver'

OllamaDriver.help 'Error: file name must be specified' if ARGV.empty?
OllamaDriver.help 'Error: invalid syntax' if ARGV.length != 1

OllamaDriver.new.summarize ARGV[0]
